//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDV_Randomizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDV_Randomizer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrobat.
        /// </summary>
        public static string AcrobatName {
            get {
                return ResourceManager.GetString("AcrobatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antiquarian.
        /// </summary>
        public static string AntiquarianName {
            get {
                return ResourceManager.GetString("AntiquarianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe Boy.
        /// </summary>
        public static string AxeBoyName {
            get {
                return ResourceManager.GetString("AxeBoyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barmaid.
        /// </summary>
        public static string BarmaidName {
            get {
                return ResourceManager.GetString("BarmaidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batter.
        /// </summary>
        public static string BatterName {
            get {
                return ResourceManager.GetString("BatterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloody Queen.
        /// </summary>
        public static string BloodyQueenName {
            get {
                return ResourceManager.GetString("BloodyQueenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Breaking Wheel.
        /// </summary>
        public static string BreakingWheelName {
            get {
                return ResourceManager.GetString("BreakingWheelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clerk.
        /// </summary>
        public static string ClerkName {
            get {
                return ResourceManager.GetString("ClerkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        public static string ComposerName {
            get {
                return ResourceManager.GetString("ComposerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.
        /// </summary>
        public static string CoordinatorName {
            get {
                return ResourceManager.GetString("CoordinatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cowboy.
        /// </summary>
        public static string CowboyName {
            get {
                return ResourceManager.GetString("CowboyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Disciple&quot;.
        /// </summary>
        public static string DiscipleName {
            get {
                return ResourceManager.GetString("DiscipleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dream Witch.
        /// </summary>
        public static string DreamWitchName {
            get {
                return ResourceManager.GetString("DreamWitchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embalmer.
        /// </summary>
        public static string EmbalmerName {
            get {
                return ResourceManager.GetString("EmbalmerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchantress.
        /// </summary>
        public static string EnchantressName {
            get {
                return ResourceManager.GetString("EnchantressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entomologist.
        /// </summary>
        public static string EntomologistName {
            get {
                return ResourceManager.GetString("EntomologistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evil Reptilian.
        /// </summary>
        public static string EvilReptilianName {
            get {
                return ResourceManager.GetString("EvilReptilianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        public static string ExplorerName {
            get {
                return ResourceManager.GetString("ExplorerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Feaster.
        /// </summary>
        public static string FeasterName {
            get {
                return ResourceManager.GetString("FeasterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female Dancer.
        /// </summary>
        public static string FemaleDancerName {
            get {
                return ResourceManager.GetString("FemaleDancerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Officer.
        /// </summary>
        public static string FirstOfficerName {
            get {
                return ResourceManager.GetString("FirstOfficerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string ForwardName {
            get {
                return ResourceManager.GetString("ForwardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamekeeper.
        /// </summary>
        public static string GamekeeperName {
            get {
                return ResourceManager.GetString("GamekeeperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardener.
        /// </summary>
        public static string GardenerName {
            get {
                return ResourceManager.GetString("GardenerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geisha.
        /// </summary>
        public static string GeishaName {
            get {
                return ResourceManager.GetString("GeishaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grave Keeper.
        /// </summary>
        public static string GraveKeeperName {
            get {
                return ResourceManager.GetString("GraveKeeperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard 26.
        /// </summary>
        public static string Guard26Name {
            get {
                return ResourceManager.GetString("Guard26Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hell Ember.
        /// </summary>
        public static string HellEmberName {
            get {
                return ResourceManager.GetString("HellEmberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hermit.
        /// </summary>
        public static string HermitName {
            get {
                return ResourceManager.GetString("HermitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journalist.
        /// </summary>
        public static string JournalistName {
            get {
                return ResourceManager.GetString("JournalistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyer.
        /// </summary>
        public static string LawyerName {
            get {
                return ResourceManager.GetString("LawyerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Little Girl&quot;.
        /// </summary>
        public static string LittleGirlName {
            get {
                return ResourceManager.GetString("LittleGirlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky Guy.
        /// </summary>
        public static string LuckyGuyName {
            get {
                return ResourceManager.GetString("LuckyGuyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mad Eyes.
        /// </summary>
        public static string MadEyesName {
            get {
                return ResourceManager.GetString("MadEyesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magician.
        /// </summary>
        public static string MagicianName {
            get {
                return ResourceManager.GetString("MagicianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanic.
        /// </summary>
        public static string MechanicName {
            get {
                return ResourceManager.GetString("MechanicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercenary.
        /// </summary>
        public static string MercenaryName {
            get {
                return ResourceManager.GetString("MercenaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mind&apos;s Eye.
        /// </summary>
        public static string MindsEyeName {
            get {
                return ResourceManager.GetString("MindsEyeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naid.
        /// </summary>
        public static string NaiadName {
            get {
                return ResourceManager.GetString("NaiadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nightmare&quot;.
        /// </summary>
        public static string NightmareName {
            get {
                return ResourceManager.GetString("NightmareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Watch.
        /// </summary>
        public static string NightWatchName {
            get {
                return ResourceManager.GetString("NightWatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novelist.
        /// </summary>
        public static string NovelistName {
            get {
                return ResourceManager.GetString("NovelistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painter.
        /// </summary>
        public static string PainterName {
            get {
                return ResourceManager.GetString("PainterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfurmer.
        /// </summary>
        public static string PerfumerName {
            get {
                return ResourceManager.GetString("PerfumerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer.
        /// </summary>
        public static string PhotographerNamer {
            get {
                return ResourceManager.GetString("PhotographerNamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postman.
        /// </summary>
        public static string PostmanName {
            get {
                return ResourceManager.GetString("PostmanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priestess.
        /// </summary>
        public static string PriestessName {
            get {
                return ResourceManager.GetString("PriestessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Prisoner&quot;.
        /// </summary>
        public static string PrisonerName {
            get {
                return ResourceManager.GetString("PrisonerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        public static string ProfessorName {
            get {
                return ResourceManager.GetString("ProfessorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospector.
        /// </summary>
        public static string ProspectorName {
            get {
                return ResourceManager.GetString("ProspectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Psychologist&quot;.
        /// </summary>
        public static string PsychologistName {
            get {
                return ResourceManager.GetString("PsychologistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ripper.
        /// </summary>
        public static string RipperName {
            get {
                return ResourceManager.GetString("RipperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sculptor.
        /// </summary>
        public static string SculptorName {
            get {
                return ResourceManager.GetString("SculptorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seer.
        /// </summary>
        public static string SeerName {
            get {
                return ResourceManager.GetString("SeerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiley Face.
        /// </summary>
        public static string SmileyFaceName {
            get {
                return ResourceManager.GetString("SmileyFaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul Weaver.
        /// </summary>
        public static string SoulWeaverName {
            get {
                return ResourceManager.GetString("SoulWeaverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thief.
        /// </summary>
        public static string ThiefName {
            get {
                return ResourceManager.GetString("ThiefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toy Merchant.
        /// </summary>
        public static string ToyMerchantName {
            get {
                return ResourceManager.GetString("ToyMerchantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Undead&quot;.
        /// </summary>
        public static string UndeadName {
            get {
                return ResourceManager.GetString("UndeadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violonist.
        /// </summary>
        public static string ViolonistName {
            get {
                return ResourceManager.GetString("ViolonistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wax Artist.
        /// </summary>
        public static string WaxArtistName {
            get {
                return ResourceManager.GetString("WaxArtistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeping Clown.
        /// </summary>
        public static string WeepingClownName {
            get {
                return ResourceManager.GetString("WeepingClownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildling.
        /// </summary>
        public static string WildlingName {
            get {
                return ResourceManager.GetString("WildlingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wu Chang.
        /// </summary>
        public static string WuChangName {
            get {
                return ResourceManager.GetString("WuChangName", resourceCulture);
            }
        }
    }
}
